---
- name: copy Dockerfile to server
  copy: src=docker-cpp dest=/home/{{ ansible_ssh_user }}

- name: build C++ client
  sudo: true  
  docker_image:
      path: /home/{{ ansible_ssh_user }}/docker-cpp
      name: cpp
      state: build
  async: 1200
  poll: 5

- name: start ethereum client w/ JSON-RPC and bootstrapping  
  sudo: true
  docker: 
      image:    cpp
      expose:   ["8080", "30303"]
      ports:    ["8080:8080", "30303:30303"] 
      
      # parameters given to client 
      command: --bootstrap --json-rpc
