---
- name: Terminate all ec2 instances 
  hosts: security_group_eth-netstat
  remote_user: ubuntu 
  gather_facts: false
  roles:
      - ec2

  tasks:
      - include: roles/ec2/tasks/terminate.yml
